# -*- coding: utf-8 -*-
"""Week3-A108260048-廖凰君.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19NuU0JDXhAOteGXJUQOxyeJYkMh1WWdJ
"""

print("Hello World")

